name: core_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.1.0
  easy_stepper: ^0.8.3
  firebase: ^9.0.3
  firebase_core: ^3.2.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  go_router: ^14.1.1
  google_fonts: ^4.0.4
  intl: ^0.19.0
  mqtt_client: ^10.3.0
  provider: ^6.1.2
  quickalert: ^1.1.0
  syncfusion_flutter_charts: ^26.1.41+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/illustration/
    - assets/logo/
    - env
